### ISSUE TITLE
Support final release of Angular 2

### ISSUE THREAD

**Issue by nelsonmorais** [sureshchahal/angular2-adal#3]
Apparently the current version does not support the final version of Angular 2 as reported in this link also: https://github.com/alenny/angular2-adal/issues/14 which points to the original angular2-adal repo.

Can this be fixed in ng2-adal?

**Comment by sureshchahal** [comment]
Sure I will try but very tight on bandwidth. I will appreciate if someone
can pick up some issues

**Comment by sureshchahal** [comment]
Upgraded to 2.0 but still need to expose it via modules

**Comment by nelsonmorais** [comment]
@sureshchahal Thanks!

I'm trying it out. For the moment by copying the ts and services folders to my project from the npm package and by changing the core.ts to be:

`
// import {provide} from "@angular/core"; <== No longer supported in Angular 2 final release
import {AdalService} from "./services";

export \* from "./services";

export const ANGULAR2_ADAL_PROVIDERS: any[] = [
    // provide(AdalService, {useClass: AdalService})  <== No longer supported in Angular 2 final release
    {
        provide: AdalService,
        useClass: AdalService
    }
];
`

I was able to use it, so I think that to completely update the npm package to be valid for Angular 2 the change above (without the commented code :)) needs to be in place.

**Comment by isaacrlevin** [comment]
@nelsonmorais Would you mind sharing a sample of this working in Angular 2 Release?

**Comment by sureshchahal** [comment]
@nelsonmorais thanks for code. I have fixed and uploaded new release.

**Comment by nelsonmorais** [comment]
@sureshchahal Did you also updated the npm package? I'm still getting the same code when I installed the npm package.

**Comment by MikeLallemont** [comment]
Has this package been updated for Angular 2.0.0+ and if so how can I integrate it using webpack?

**Comment by MikeLallemont** [comment]
After installing ng2-adal using npm I am trying to:

```
import { AdalService } from 'ng2-adal/core';

@NgModule({
  declarations: [
    ClientApp
  ],
  imports: [
    HttpModule,
    IonicModule.forRoot(ClientApp, {}, navigationProvider.deepLinks),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (http: Http) => new TranslateStaticLoader(http, '/assets/i18n', '.json'),
      deps: [Http]
    }),
    ReactiveFormsModule,
    WjCoreModule,
    WjGridModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    ClientApp
  ],
  providers: [
    AdalService,
    AuthenticationProvider
  ]
})
export class AppModule { }

```

I get an error when I run the app:
adal.service.js:21Uncaught Error: Cannot find module "adal"(…)

Any help is extremely appreciated. Thank you!!

**Comment by sureshchahal** [comment]
include this in systemjs.config

'adal':'npm:ng2-adal/node_modules/adal-angular/lib'

also for more details you can refer

https://github.com/sureshchahal/ng2-adal-examples

**Comment by MikeLallemont** [comment]
That is my main problem, I am using webpack I have no idea how what you have in system.config.js relates to what I need in webpack.

**Comment by sureshchahal** [comment]
reason for this issue is that there were no typings for adal, which is js
powering the adal authentication. If you have some concept like typings in
webpack, try that. I do not know webpack, so could not provide more details

**Comment by MikeLallemont** [comment]
I installed with npm @types/adal but it did not solve the problem of finding the adal module. 

Am I importing the correct file? import { AdalService } from 'ng2-adal/core';

And specifying it correctly in my @NgModule config?

**Comment by fume** [comment]
Hi @MikeLallemont ,
you should resolve the issue editing your webpack config.

Add this:
`resolve: {
        alias: { 'adal': 'adal-angular' }
    }
`
If the "resolve" section doesn't exist, add it.

Edit:
Here webpack docs about resolve-alias: https://webpack.github.io/docs/configuration.html#resolve-alias

Regards,

**Comment by MikeLallemont** [comment]
Thank you so much, that solved my problem. 

I said a little prayer at lunch and this was waiting for me when I got back! :)

**Comment by sureshchahal** [comment]
@nelsonmorais i just published the package to NPM. please check

**Comment by nelsonmorais** [comment]
Hi @sureshchahal !
Thanks for the update :)! I'll give it a try and see if it's working and I'll share my findings here.

**Comment by nelsonmorais** [comment]
Hi @isaac2004,
Unfortunately I can't share the code I have, sorry for that :(.
I have Webpack 1.13.3 working with the Angular 2.1.1 and I've applied the the fix I posted in this thread (see comments above) for ng2-adal.
I'll also try the latest change made by @isaac2004 to see if I can now use the npm ng2-adal package directly instead of having it copied and modified in my app code.
I'll share the results here as soon as I update my app to use the updated version.

**Comment by MikeLallemont** [comment]
I see references to ng2-adal which is the library I'm using, but our discussion is here on angular2-adal. Are they both the same? if not what is the difference?

**Comment by sureshchahal** [comment]
@MikeLallemont  ng2-adal is forked from angular2-adal. Since angular2-adal is not active now(my pull request in now pending for more than 2 month), ng2-adal package was published. this  is active and with bug fixes and new functionality like  auto authenticating backend API calls , fixing issues with handlewindowcallback, angular2 support

**Comment by isaacrlevin** [comment]
One thing I noticed is that only one of the files from adal angular is being referenced. There are 2 files (one does the general auth, the other handles subsequent requests) in the lib folder. The adal.js file is being referenced but adal-angular.js is not. Can you make change to your bundler to add this file and publish to NPM?

**Comment by sureshchahal** [comment]
@isaac2004   adal-angular.js is angular 1.x wrapper on adal.js. in ng2-adal there is a AuthHttp  class, whch handles attaching access code to subsequent request.

**Comment by fume** [comment]
I guess this issue should be closed: now we are using angular2 final. Maybe we need another issue: Use NgModule

**Comment by sureshchahal** [comment]
closing this as @fume opened new issue for NgModule

**Comment by nelsonmorais** [comment]
I've checked the changes made by @isaac2004  and I was able to use the npm module directly now.
@isaac2004 Thanks!

My config is:
Angular 2 + WebPack + ng2-adal (0.2.4)

**Comment by fume** [comment]
@nelsonmorais Are you talking about my last PR? If so, i'm so glad to hear that from you even if you mentioned the wrong guy :)

**Comment by MikeLallemont** [comment]
Hey guys, I have an interesting event going on here. 

I have the app build working with no errors, but my co-worker, who is doing a build on his Windows machine gets an error when building. It appears that he gets the error when the transpiler is looking for the alias ‘adal’ which is handled in the webpack config as you described below. His build process never gets to see the ‘webpack started’ message since it errors out first. Here is my console output:

> ionic-app-scripts build

[13:38:10]  ionic-app-scripts 0.0.41
[13:38:10]  build dev started ...
[13:38:10]  clean started ...
[13:38:10]  clean finished in 8 ms
[13:38:10]  copy started ...
[13:38:10]  transpile started ...
[13:38:10]  lint started ...
[13:38:11]  lint finished in 1.29 s
[13:38:13]  transpile finished in 3.15 s
[13:38:13]  webpack started ...
[13:38:13]  copy finished in 3.25 s
[13:38:20]  webpack finished in 6.70 s
[13:38:20]  sass started ...
[13:38:21]  sass finished in 1.32 s
[13:38:21]  build dev finished in 11.19 s 

His gets an error right after ‘lint finished’. 

Any thoughts?

**Comment by MikeLallemont** [comment]
Oh and here is the windows build output: 

> ionic-app-scripts build

[08:36:14]  ionic-app-scripts 0.0.39
[08:36:14]  build dev started ...
[08:36:14]  clean started ...
[08:36:14]  clean finished in 7 ms
[08:36:14]  copy started ...
[08:36:14]  transpile started ...
[08:36:15]  lint started ...
[08:36:17]  lint finished in 2.09 s
[08:36:18]  typescript: C:/POCWork/ClientApp/node_modules/ng2-adal/services/adal.service.d.ts, line: 14
            Cannot find namespace 'adal'.

```
  L13:  logOut(): void;
  L14:  handleWindowCallback(): void;
  L15:  getCachedToken(resource: string): string;
```

[08:36:18]  typescript: C:/POCWork/ClientApp/node_modules/ng2-adal/services/adal.service.d.ts, line: 15
            Cannot find namespace 'adal'.

```
  L14:  handleWindowCallback(): void;
  L15:  getCachedToken(resource: string): string;
  L16:  acquireToken(resource: string): Observable<{}>;
```

[08:36:18]  typescript: C:/POCWork/ClientApp/node_modules/ng2-adal/services/adal.service.d.ts, line: 23
            Cannot find namespace 'adal'.

```
  L22:  GetResourceForEndpoint(url: string): string;
  L23:  private updateDataFromCache(resource);
```

[08:36:18]  transpile failed
[08:36:18]  ionic-app-script task: "build"
[08:36:18]  Error: Error

**Comment by isaacrlevin** [comment]
Global typings maybe?

**Comment by MikeLallemont** [comment]
@isaac2004 Is it using typings? I thought it was now using the @type/adal npm package. Are you referring to different versions of typings installed globally?

**Comment by isaacrlevin** [comment]
That or having to do an alias of the typing

**Comment by nelsonmorais** [comment]
@MikeLallemont @type/adal is outdated, it targets adal 1.0.8 and the latest adal is 1.0.12.
In @type/adal the field "instance" is missing on the adal.Config but it is available in the index.d.ts in the ng2-adal\ts\ada\index.d.ts.

**Comment by MikeLallemont** [comment]
Here is the section of my package.json that shows adal:

`"devDependencies": {
    "@ionic/app-scripts": "0.0.43",
    "@types/adal": "^1.0.22",
    "@types/chai": "^3.4.34",
    "typescript": "2.0.6"
  },
`

Do I still need this resolve in my webpack config?

`resolve: {
    extensions: ['.js', '.ts', '.json'],
    alias: { 'adal': 'adal-angular' }        
  },
`

Is there a newer version that does not require the alias?

**Comment by MikeLallemont** [comment]
Is there another way to resolve this even if I'm using wepack without using the alias? 

Maybe:

`import adal-angular as adal from 'path-to-adal-angular';
`

It seems to me you guys should make it to where we do not need to do anything special in webpack config to make it work. It works ok for me, but my Windows guy cannot get it to build. And we are using a Windows based CI server.

**Comment by isaacrlevin** [comment]
Here is my webpack file that works fine

```
   resolve: {
        alias: { 'adal': 'adal-angular' }
    },
```

**Comment by MikeLallemont** [comment]
That works fine on my machine too, but on my co-worker's Windows machine it fails compiling because it cannot find 'adal'. Let me update everything to the latest versions and see what happens.

**Comment by isaacrlevin** [comment]
I am on windows, no additional commands. try an npm install and start again

**Comment by fume** [comment]
You are talking about two different issues. Webpack aliases will never let your code COMPILE. Your problem is about adal typings!! Have you referenced them correctly on your ts file as showed on the npm package page?

**Comment by MikeLallemont** [comment]
Here is my package.json:

```
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "^2.2.3",
    "ionicons": "3.0.0",
    "ng2-adal": "0.2.4",
    "ng2-translate": "3.1.2",
    "rxjs": "5.0.0-beta.12",
    "wijmo": "file:./local_modules/wijmo-amd",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.43",
    "@types/adal": "^1.0.22",
    "@types/chai": "^3.4.34",
    "typescript": "2.0.6"
  },
```

Is there anything missing? Not correct?

**Comment by MikeLallemont** [comment]
@fume Is there a typings definition I'm missing?

**Comment by fume** [comment]
i never used @types/adal .
I guess you should use the one included IN the package as described here (at the end): https://www.npmjs.com/package/ng2-adal
OR here: https://github.com/sureshchahal/angular2-adal/issues/5

We should continue the discussion in issue https://github.com/sureshchahal/angular2-adal/issues/5
because we're talking about THAT! This one is closed and is completely different from the one you're experiencing.

**Comment by MikeLallemont** [comment]
I thought using the npm package @types/adal was the latest way to use type definitions and having a typings folder typings.json was the old way. If I'm doing out wrong I wish someone would tell me the correct way to do it.

**Comment by galvanu** [comment]
I'm getting the following error while trying to integrate it with angular-cli project:

ERROR in ./~/ng2-adal/services/adal.service.js
Module not found: Error: Can't resolve 'adal' in '/Users/user/Workspace/project/node_modules/ng2-adal/services'
 @ ./~/ng2-adal/services/adal.service.js 21:14-29
 @ ./~/ng2-adal/services.js
 @ ./~/ng2-adal/core.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

angular-cli version beta20-4 uses webpack and doesn't exposed the webpack.config.json.
Do you have any idea how can I solve this?

**Comment by WhitWaldo** [comment]
@galvanu I'm not using Webpack myself, but rather systemjs, so there may be different terminology, but adal.js is included in the package. I had to set up my own alias to it (look inside the node_modules folder in the package) and then it worked for me.

**Comment by galvanu** [comment]
@Xaniff thanks for the help. I really tried everything but I think i still missing something.

Can someone help me with the integration with ng-cli?

**Comment by isaacrlevin** [comment]
I am using WebPack and all I had to do was add a resolve alias

```
    resolve: {
       alias: { 'adal': 'adal-angular' }
    },
```

**Comment by galvanu** [comment]
@isaac2004 thanks for the help, I tried to do that but the problem is I don't have webpack.config.json file. There is any change the latest version of angular-cli doesn't generate it?

**Comment by isaacrlevin** [comment]
Sorry I have no experience using angular cli..... There has to be a way to
customize webpack however it has no value

**Comment by MikeLallemont** [comment]
@isaac2004 If you are using Ionic, you can create a custom configuration for webpack and reference it in your package.json. Also this is what fixed the problem for me:

I took out the @types/adal package because it did not work in a Windows environment which is what my client uses. 

Then I added this line of code to top of my main.dev.ts and main.prod.ts files:

`///<reference path="../../node_modules/ng2-adal/ts/adal/index.d.ts"/>
`
